language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: leopetr95
    token: 07cad854cf2c3f69cfd32941f4b45db39176557d
script:

  # -Dtest=... --> Indica la classe di test da eseguire
  - mvn verify -e -DfailIfNoTests=false -Dmaven.javadoc.skip=true sonar:sonar -Pcode-coverage -Dsonar.projectKey=leopetr95_zookeeper -Dmaven.test.failure.ignore=true
